---
- name: "Build docker images and push them to GCR"
  hosts: localhost
  gather_facts: false
  tasks:
  - name: "Get timestamp for docker tag"
    shell: "(date +%Y%m%d%H%M%S)"
    register: tag
  - name: Print tag
    debug:
      var: tag
  - name: Build frontend container image
    community.general.docker_image:
      build:
        path: /frontend
      name: gcr.io/{{ gcp_project }}/drowsiness-app-frontend:{{ tag.stdout}}
      source: build
  - name: Push frontend image to GCR
    community.general.docker_image:
      name: gcr.io/{{ gcp_project }}/drowsiness-app-frontend:{{ tag.stdout}}
      repository: gcr.io/{{ gcp_project }}/drowsiness-app-frontend:{{ tag.stdout}}
      push: yes
      source: local
  - name: "Save docker tag"
    shell: echo {{ tag.stdout}} > .docker-tag